services:
  ph-sensor:
    build:
      context: ./sensor
    command:
      - --id=ph_sensor_0
      - --base-url=http://server

  temp-sensor:
    build:
      context: ./sensor
    command:
      - --id=temp_sensor_0
      - --base-url=http://server

  server:
    build:
      context: ./server
    ports:
      - "8000:80"
